### PR TITLE
fix(tar): read full extended headers

### LINKED ISSUE #383: "Item with the same key has already been added" extracting tar with duplicate headers
SharpZipLib fails to process a tar file that contains duplicate extended headers. Other tar programs (e.g. tar, 7-zip, SharpCompress) appear to handle this fine.

### Steps to reproduce
1. Download https://registry.npmjs.org/jasmine-data-provider/-/jasmine-data-provider-2.2.0.tgz
2. gunzip (either with sharpziplib or other software)
3. Attempt to extract, read entries, or list contents of the tar:
```cs
using (var fs = File.OpenRead("c:\\jasmine-data-provider-2.2.0.tar"))
using (TarArchive tar = TarArchive.CreateInputTarArchive(fs))
{
    tar.ListContents();
}
```

### Actual behavior

>An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)   at ICSharpCode.SharpZipLib.Tar.TarExtendedHeaderReader.Read(Byte[] buffer, Int32 length)   at ICSharpCode.SharpZipLib.Tar.TarInputStream.GetNextEntry()   at ICSharpCode.SharpZipLib.Tar.TarArchive.ListContents()

### Version of SharpZipLib
1.2.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

### PR DESCRIPTION
**Pull request by piksel**
Fixes #383, but is not the most elegant solution. `TarExtendedHeaderReader` should probably be rewritten from scratch.

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

File: src/ICSharpCode.SharpZipLib/Tar/TarExtendedHeaderReader.cs [hunk 1]
```diff
@@ -46,23 +50,47 @@ public void Read(byte[] buffer, int length)
...
 				{
 					Flush();
 					headerParts[state] = sb.ToString();
 					sb.Clear();
-
+					
 					if (++state == END)
 					{
-						headers.Add(headerParts[KEY], headerParts[VALUE]);
+						Console.WriteLine($"KEY: {headerParts[KEY]}");
```
Comment (piksel) [inline src/ICSharpCode.SharpZipLib/Tar/TarExtendedHeaderReader.cs:66]:
```suggestion
```
