### PR TITLE
Throw exception on Store+Descriptor entries

### LINKED ISSUE #15: ZipInputStream class doesn't process correctly no compression entries with flag Bit 3 set
The PKZIP documentation [here](http://www.pkware.com/documents/casestudies/APPNOTE.TXT) states for general purpose flag Bit 3:

"If this bit is set, the fields crc-32, compressed size and uncompressed size are set to zero in the local header.  The correct values are put in the data descriptor immediately following the compressed data.  (Note: PKZIP version 2.04g for DOS only recognizes this bit for method 8 compression, newer versions of PKZIP recognize this bit for any compression method.)".

---

The CRC, compressed and uncompressed size will be 0 and the extraction fails.

### PR DESCRIPTION
**Pull request by piksel**
Due to the way that ZipInputStream is designed, reading entries that are using `Store` compression method and `Descriptor` flag is not possible. This change will throw a `StreamUnsupportedException` instead of failing on incorrect CRC.

Fixes #15 (as much as a fix as is possible for this).

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by Numpsy** [comment]
Should ```ZipInputStream.CanDecompressEntry``` return false for these entries?

**Comment by piksel** [comment]
> Should `ZipInputStream.CanDecompressEntry` return false for these entries?

Good point! It should. That is the most elegant way to handle it for the consumer.

File: src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs [hunk 1]
```diff
@@ -861,42 +722,29 @@ public long Crc
 		}
 
 		/// <summary>
-		/// Gets/Sets the compression method. Only Deflated and Stored are supported.
+		/// Gets/Sets the compression method. Only <see cref="CompressionMethod.Deflated">Deflated</see>
```
Comment (Numpsy) [inline src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs:725]: Not related to this actual issue, but that's out of date - BZip2 is supported in the ZipFile case now

File: src/ICSharpCode.SharpZipLib/Zip/ZipEntryExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,32 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace ICSharpCode.SharpZipLib.Zip
+{
+	/// <summary>
+	/// General ZipEntry helper extensions
+	/// </summary>
+	public static class ZipEntryExtensions
```
Comment (Numpsy) [inline src/ICSharpCode.SharpZipLib/Zip/ZipEntryExtensions.cs:10]: Does it need to be public? (not sure if it's useful for other users or not?)

Comment (piksel) [reply src/ICSharpCode.SharpZipLib/Zip/ZipEntryExtensions.cs:10]: Maybe not, but I know that I would appreciate having it when consuming the library (since the flag is exposed in a public property as an `int`).

File: src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs (hunk 1 above)
Comment (piksel) [reply src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs:725]: Yeah, that's the problem with having this logic in `ZipEntry`. I wonder if we even should limit this here. It should be up to `ZipFile` and `ZipOutputStream` to throw on adding such an entry.

Comment (Numpsy) [reply src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs:725]: refs #500

File: src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs [hunk 3]
```diff
@@ -512,11 +512,13 @@ private int ReadingNotSupported(byte[] destination, int offset, int count)
 		/// <returns>The actual number of bytes read.</returns>
 		private int InitialRead(byte[] destination, int offset, int count)
 		{
-			if (!CanDecompressEntry)
+			if (entry == null)
```
Comment (Numpsy) [inline src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs:515]: I don't think it should be possible to get here in that case? (maybe  auseful sanity check in case though)

Comment (piksel) [reply src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs:515]: No, I don't think so either, but since the `CanDecompressEntry` used to check it, I didn't want to remove it since the rest of the body dereferences entity a lot. It shouldn't be too hard to verify though.

Comment (Numpsy) [reply src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs:515]: I was going to query if changing this effects the handling of AES entries (where the 'entry.IsCrypted' path only handles ZipCrypto entries), but I don't *think* it can get this far for those because of the earlier checks in GetNextEntry.

Comment (piksel) [reply src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs]: Yeah, exactly. There is only one reference to the method, and that method sets and dereferences entity just before invoking this one. Hence I removed the check.

**Comment by Numpsy** [comment]
On another trivial not-directly-related-to-this-issue thought:

looking at the code just made me wonder if there enough instances of

```
if (entry.AESKeySize > 0)
```

use purely as a 'should the entry be AES encrypted' check to make it worth adding something like a

```
internal bool IsAESEncrypted => _aesEncryptionStrength > 0;
```

property to ZipEntry, even if only as an internal helper?

**Comment by Numpsy** [comment]
Changes seem ok otherwise though

**Comment by piksel** [comment]
Note that the reason for it immediately throwing in `InitialRead` (by invoking `StoredDescriptorEntry`) AND setting the read method to `StoredDescriptorEntry` is that in this situation, it's not just reading the entry data that is not possible. It's also not possible to skip it/seek to the next entry. This does however give the consumer a chance to read everything up to this entry and detect that such an entry was found. Perhaps not something anyone will use, but it feels like the "correct" way to handle it at least.

File: src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs [hunk 4]
```diff
@@ -503,10 +512,7 @@ private int ReadingNotSupported(byte[] destination, int offset, int count)
 		/// <returns>The actual number of bytes read.</returns>
 		private int InitialRead(byte[] destination, int offset, int count)
 		{
-			if (!CanDecompressEntry)
-			{
-				throw new ZipException("Library cannot extract this entry. Version required is (" + entry.Version + ")");
-			}
+			var usesDescriptor = (entry.Flags & (int)GeneralBitFlags.Descriptor) != 0;
```
Comment (Numpsy) [inline src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs:515]: Can that use the HasFlag helper you added?

Comment (piksel) [reply src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs:515]: There's a lot of places where it can be used, but this is essential the same as using that method. It might be a bit easier to read, but the main issue I had were the places where the flags where compared to a magic number instead. Really opaque to the reader.
Anyhow, I won't add any more changes of that type to this PR, but I'll instead merge it so that it can be used in subsequent PRs.
