### PR TITLE
Use RNGCryptoServiceProvider for crypto headers

### LINKED ISSUE #536: Random() is not secure because it provides insufficient entropy. CWE ID 331.
### Steps to reproduce
1. Static code security scan.  Example:
```
		private static void WriteEncryptionHeader(Stream stream, long crcValue)
		{
			byte[] cryptBuffer = new byte[ZipConstants.CryptoHeaderSize];
			var rnd = new Random();
			rnd.NextBytes(cryptBuffer);
			cryptBuffer[11] = (byte)(crcValue >> 24);
			stream.Write(cryptBuffer, 0, cryptBuffer.Length);
		}
```

### Expected behavior
Replace all uses of System.Random() with a cryptographic version such as that provided by RNGCryptoServiceProvider.

### Actual behavior
SharpZipLib fails security scans.

### Version of SharpZipLib
1.3.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

### PR DESCRIPTION
**Pull request by piksel**
Use a proper RNG for cryptographically important randomness.
Fixes #536 

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by Numpsy** [comment]
Is it intentional that the ```RNGCryptoServiceProvider``` is disposed in two of those change, but not the third?

File: src/ICSharpCode.SharpZipLib/Encryption/PkzipClassic.cs [hunk 1]
```diff
@@ -444,8 +444,8 @@ public override byte[] Key
 		public override void GenerateKey()
 		{
 			key_ = new byte[12];
-			var rnd = new Random();
-			rnd.NextBytes(key_);
+			var rng = new RNGCryptoServiceProvider();
+			rng.GetBytes(key_);
```
Comment (piksel) [inline src/ICSharpCode.SharpZipLib/Encryption/PkzipClassic.cs:448]:
```suggestion
			using (var rng = new RNGCryptoServiceProvider())
			{
				rng.GetBytes(key_);
			}
```

**Comment by piksel** [comment]
> Is it intentional that the `RNGCryptoServiceProvider` is disposed in two of those changes, but not the third?

Noope.
